[pi:getToken(client_secret: PI_client_secret, client_id: PI_client_id, grant_type: "client_credentials")]
[piEcho:$]
[pi:setAuthToken(token:$.access_token)]
[pi:createNewMember(email: "your@email.address", firstName: "Will", lastName: "Stafford")]
[piEcho:$]
[pi:loginUser(username:"test@testMember.com", password:"test123", client_id: PI_client_id, client_secret: PI_client_secret, grant_type: "password")]
[piDefine:$->testUserAuth]
[piEcho:testUserAuth]
[pi:setAuthToken(token: testUserAuth.access_token)]
