[piEcho:"Reg User: " + PI_member]
[pi:getToken(client_secret: PI_client_secret, client_id: PI_client_id, grant_type: "client_credentials")]
[piEcho:$]
[pi:setAuthToken(token:$.access_token)]
[pi:createNewMember(email: PI_member, firstName: "Will", lastName: "Staffquad")]
[piEcho:$]
[pi:loginUser(username:"test@testMember.com", password:"test123", client_id: PI_client_id, client_secret: PI_client_secret, grant_type: "password")]
[piEcho: $]